version: '3.8'

services:
    db:
        image: mongo
        restart: always
        volumes:
            - /mongodb:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017
    api:
        build: .
        container_name: quality-lib-api
        restart: always
        volumes:
            - .:/usr/app
        ports:
            - 3005:3005
        depends_on:
            - db
