version: '3.8'

services:
    db:
        image: mongo
        restart: always
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
    api:
        build: .
        container_name: quality-lib-api
        restart: always
        volumes:
            - .:/usr/app
        ports:
            - 3005:3005
        links:
            - db
        depends_on:
            - db
